### ISSUE TITLE
How to use code to collect trajectory？ How to use LLM-as-a-judge to evaluate the code generation result？

### ISSUE THREAD

**Issue by zhang123434** [metauto-ai/agent-as-a-judge#20]
Hello, thank you for your great work. @mczhuge
#First question:
In your paper's fifth page, there is a sentence: "we record key decisions and actions made by the agentic systems through some custom instrumentation code, resulting in a development trajectory for each of the agentic systems." It seems that the mentioned custom instrumentation code is not open-sourced. Can we use code to automatically generate trajectory ?
#Second question:
How to use LLM-as-a-judge to evaluate the code generation result？What is the specific setting?

**Comment by mczhuge** [comment]
Dear @zhang123434,

Thank you for your kind words!

1. The frameworks we used are open-source, and it's straightforward to obtain the trajectories with just a few hours of coding. We have provided a suggested format for the trajectories:

   - **Format:** [trajectory-schema.json](https://github.com/metauto-ai/agent-as-a-judge/blob/main/benchmark/devai/trajectory-schema.json)
   - **Validation Tool:** [validate_trajectory.py](https://github.com/metauto-ai/agent-as-a-judge/blob/main/benchmark/devai/validate_trajectory.py)
   - **Sample Trajectory:** [OpenHands Sample](https://github.com/metauto-ai/agent-as-a-judge/blob/main/benchmark/trajectories/OpenHands/39_Drug_Response_Prediction_SVM_GDSC_ML.json)

2. For the LLM-as-a-Judge baselines, we directly input the workspace information into the LLMs.

If you have any more questions or need further assistance, feel free to ask!

**Comment by zhang123434** [comment]
Thanks for your response!
Do you mean that the frameowork（MetaGPT, OpenHands, GPT-Pilot）can automatically generate the trajectory？

Besides, in the https://github.com/metauto-ai/agent-as-a-judge/blob/main/scripts/README.md, the fourth command :
Do not have trajectories or development logs and using planning to decide the actions of Agent-as-a-Judge (**black-box setting)**
```
PYTHONPATH=. python scripts/run_aaaj.py \
  --developer_agent "OpenHands" \
  --setting "gray_box" \
  --planning "planning" \
  --benchmark_dir $(pwd)/benchmark
```
```--setting "gray box"``` in the command should be replaced with ```--setting "black_box"```?

**Comment by mczhuge** [comment]
Yes. Since the trajectories and workspaces are easily generated by other open-sourced frameworks by injecting several lines of code in the right place (such as the agent's thought, the agent's action, and the environment feedback). 

Yes. Set to the "black_box"

**Comment by HaokunLiu** [comment]
Hello, congrats on this amazing work.
Our lab doesn't sponsor OpenAI API. Would it be possible to share the trajectories you collected for the 55 problems from the three agent systems?
